Document: piratepack
Title: Debian piratepack Manual
Author: <insert document author here>
Abstract: This manual describes what piratepack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piratepack/piratepack.sgml.gz

Format: postscript
Files: /usr/share/doc/piratepack/piratepack.ps.gz

Format: text
Files: /usr/share/doc/piratepack/piratepack.text.gz

Format: HTML
Index: /usr/share/doc/piratepack/html/index.html
Files: /usr/share/doc/piratepack/html/*.html
