#!/bin/bash

curdir="$(pwd)"
cd
homedir="$(pwd)"

nvid=0
maxnvid=0
madedir=0
ivid=1

while read -r line
do
    nvid="${line:9}"
    if ! [[ "$nvid" =~ ^[0-9]+$ ]]
    then
        continue
    fi
    if [ "$nvid" -gt "$maxnvid" ]
    then
	maxnvid="$nvid"
    fi
    if [[ "$nvid" != "$ivid" ]]
    then
	nvid="$ivid"
	mkdir .vidalia_"$nvid"
	madedir=1
	break
    fi
    let ivid=ivid+1
    pid="$(cat "$line"/vidalia.pid 2>> /dev/null)"
    psline="$(ps -p "$pid" 2>> /dev/null | grep "$pid")"
    echo "$psline"
    if [[ x"$psline" != x"" ]]
    then
	echo "not empty"
	continue
    fi
    rm -rf "$line" 2>> /dev/null
    if [ -e "$line" ]
    then
	continue
    fi
    mkdir "$line"
    madedir=1
    break
done < <(find ".vidalia_"* -maxdepth 0 2>> /dev/null | sort)

if [[ "$madedir" == "0" ]]
then
    let nvid=maxnvid+1
    mkdir .vidalia_"$nvid"
fi

cd .vidalia_"$nvid"

cp -r "$maindir"/share/tor-browser/.vidalia/* ./

sport=$(expr 9048 + 2 \* $nvid)
cport=$(expr $sport + 1)

awk '{sub(/SocksPort[ ]9050/,"'"SocksPort $sport"'"); print}' torrc > torrc_tmp
mv torrc_tmp torrc
awk '{sub(/ControlPort[ ]9051/,"'"ControlPort $cport"'"); print}' torrc > torrc_tmp
mv torrc_tmp torrc
awk '{sub(/ControlPort[=]9051/,"'"ControlPort=$cport"'"); print}' vidalia.conf > vidalia.conf_tmp
mv vidalia.conf_tmp vidalia.conf

echo "DataDirectory ""$homedir""/.vidalia_""$nvid" >> torrc
echo "GeoIPFile ""$homedir""/.vidalia_""$nvid""/geoip" >> torrc
echo "Torrc=""$homedir""/.vidalia_""$nvid""/torrc" >> vidalia.conf
echo "DataDirectory=""$homedir""/.vidalia_""$nvid" >> vidalia.conf

cd
"$maindir"/bin/vidalia --datadir "$homedir"/.vidalia_$nvid
rm -rf "$homedir"/.vidalia_$nvid
