#!/bin/bash

cd
homedir="$(pwd)"

pid="$(cat ".vidalia_1/vidalia.pid" 2>> /dev/null)"
psline="$(ps -p "$pid" 2>> /dev/null | grep "$pid")"
if [[ x"$psline" == x"" ]]
then
    "$maindir"/bin/tor-instance &
fi

firefox -P tor -no-remote
